### ISSUE TITLE
Question: Cloudflare ENV

### ISSUE THREAD

**Issue by saliksik** [seanoliver/audioflare#7]
How will I get the following environment variables? I can only generate the AUTH Token, but I cannot find the Rest API Key.

# Cloudflare Workers AI
CLOUDFLARE_REST_API_KEY=
CLOUDFLARE_AUTH_TOKEN=3qCbUN1mZLUXXXXXXXXXXXXXXXXXXGiF

# Cloudflare AI Gateway
CLOUDFLARE_AI_GATEWAY_ENDPOINT=username
CLOUDFLARE_AI_GATEWAY_UNIVERSAL_ENDPOINT=https://gateway.ai.cloudflare.com/v1/c1b0fa89d34fa2f2e392fd5dbbca5e3e/username

**Comment by seanoliver** [comment]
Hey @saliksik! Thanks for pointing this out! I just pushed an update [here](https://github.com/seanoliver/audioflare/commit/4f63746e71eb7aa3245049ce8e60f72caff7e8bb) which I hope makes this easier.

The variable names weren't super clear, so I renamed them and added links to where you can find them. I'd also deconstructed the AI Gateway endpoint URL, so it now just uses your account ID and the URL slug based on your gateway name.

Here's what the new `.env.example` looks like! Reopen and let me know if you have trouble with any of these instructions and I'd be happy to record a screencast if that would be better.

```bash
# Cloudflare Account ID: https://developers.cloudflare.com/fundamentals/setup/find-account-and-zone-ids/
CLOUDFLARE_ACCOUNT_ID=

# Cloudflare API Token: https://developers.cloudflare.com/workers-ai/get-started/rest-api/
CLOUDFLARE_API_TOKEN=

# Cloudflare AI Gateway: https://developers.cloudflare.com/ai-gateway/get-started/creating-gateway/
CLOUDFLARE_AI_GATEWAY_ENDPOINT=https://gateway.ai.cloudflare.com/v1
CLOUDFLARE_AI_GATEWAY_URL_SLUG=
CLOUDFLARE_AI_GATEWAY_PROVIDER=workers-ai
```

**Comment by saliksik** [comment]
Thank you, it works now! Can we use Vercel Blob to store audio files, allowing us to bypass the size limit of Vercel Serverless Functions?
